apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: demo-workload-certificates
spec:
  allowed:
    dnsNames:
      values:
        - "*.apps.demo.internal"
      required: true
    isCA: false
    usages:
      - server auth
  constraints:
    minDuration: 1h
    maxDuration: 24h
    privateKey:
      algorithm: RSA
      minSize: 2048
      maxSize: 4096
  selector:
    issuerRef:
      name: demo-ca
      kind: ClusterIssuer
      group: cert-manager.io
    namespace:
      matchNames:
        - demo-app

